steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '.'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
        '--platform=$_PLATFORM',
        '--project=$PROJECT_ID',
        '--region=$_DEPLOY_REGION',
        '--allow-unauthenticated',
        '--memory=256Mi',
        'cloud-run-hackathon-elixir',
      ]
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: cloud-run-hackathon-elixir
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
