steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '.'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cloudbowl-samples-elixir:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cloudbowl-samples-elixir:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        '--image=gcr.io/$PROJECT_ID/cloudbowl-samples-elixir:$COMMIT_SHA',
        '--platform=managed',
        '--project=$PROJECT_ID',
        '--region=us-central1',
        '--allow-unauthenticated',
        '--memory=256Mi',
        'cloudbowl-samples-elixir',
      ]
